# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 15:38
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Led_State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('R', 'Rainbow'), ('RC', 'Rainbow Cycle'), ('C', 'Chase'), ('CR', 'Chase Rainbow'), ('W', 'Color Wipe'), ('CNU', 'CNU')], default='S', max_length=10)),
                ('color', colorful.fields.RGBColorField()),
            ],
        ),
    ]
